Cvd continues even if  main signatures is missing
Cisco-Talos/cvdupdate pull request #35
Opened 2021-09-15 13:17 UTC by brentclark

Good day
I would like to report and make a pull request for cvdupdate.

What we found is.
If the main / actual signature is missing (i.e. accidentally and manually removed) from the db dir, cvdupdate just continue with the cdiff(s) and ignore the fact that the main is missing.
This work will first ensure and download the main signature.

You can find the example here:
https://pastebin.com/raw/Kg4YZ6AM

Please will you consider my pull request to ensure signature integrity. 

Many thanks
Kind Regards
Brent Clark

2021-09-15 13:32 UTC, sl0m0ZA commented
This is a good update and will ensure that the signature is pulled and checked.

2021-09-16 21:03 UTC, micahsnyder commented on cvdupdate/cvdupdate.py
> +        Delete cvd controlled files in the database directory.
It appears this PR is based off of the branch including the change to only delete f"{self.db_dir / db}"`, so I will be unable to merge it until that PR is fixed and this one is based off of the fixed branch, or off of `main`.

2021-09-16 21:09 UTC, micahsnyder requested changes
This works nicely. Good fix!

I just can't merge it yet until you base it off of `main`, or until you've updated it after fixes to the other PR.

2021-09-16 21:09 UTC, micahsnyder commented on cvdupdate/cvdupdate.py
> +            if (self.db_dir / db).exists():
This change makes sense to me. 👍

2021-09-29 12:44 UTC, brentclark commented
Thanks
Can you look now please.

2022-03-12 01:56 UTC, micahsnyder commented
I see you addressed the issues I was concerned with from https://github.com/Cisco-Talos/cvdupdate/pull/34 in this PR. 
I just did some testing and it looks good. A different PR caused a big merge conflict, so I rebased your branch and fixed the conflict for you.  I wasn't about to ask you to make changes again after I made you wait so long for this re-review.  

Thank you for your patience and your contribution.

2022-03-12 01:56 UTC, merged