add Dockerfile, Dependabot & CI
Cisco-Talos/cvdupdate pull request #51
Opened 2023-02-15 14:21 UTC by monotek

This PR adds Dockerfile, Dependabot, CI and Docker release

* Dockerfile
  * uses latest python alpine image as base
  * runs a cvd update
  * runs cvd serve when executed

* Dependabot
  * updates python / pip dependencies
  * updated the Dockerfile to the latest base python alpine image

* CI
  * builds the docker image
  * runs the docker image
  * downloads main.cvd from running docker container via curl to check if everything works

* Docker release (example to push to DockerHub) using official [docker build push action](https://github.com/docker/build-push-action)
  * currently pushes to [monotek/cvdupdate](https://hub.docker.com/repository/docker/monotek/cvdupdate/tags?page=1&ordering=last_updated)
  * builds and pushes amd64 and arm64 docker images
  * pushes image when new commits in main
  * pushes image when new release / tag

The Docker release part needs to be updated to fit your registry / repo. 
The repo needs to have github action secrets for the used docker registry credentials configured. 

If wanted a Github action Cronjob could be added, to build the container every night, so clamd signatures could also be shipped through dockerhub, which might lower your traffic a bit in the longterm.

2023-02-24 10:46 UTC, monotek commented
@micahsnyder

would be nice this could get a review and some feedback :)

2023-02-24 16:39 UTC, micahsnyder commented
Hi @monotek thanks for the pull-request, and thanks for the reminder.  Sorry about the delay.  I will try to review it next week.

2023-04-14 09:51 UTC, monotek commented
@micahsnyder

do you had any chance to look into it?
can i support you in any way?

2023-05-03 14:59 UTC, monotek commented
Friendly ping :)

2023-05-24 18:41 UTC, micahsnyder commented
@monotek I'm sorry for dropping this and failing to notice the first major issue with this PR.  There is an existing work in progress to add a Dockerfile to the project: https://github.com/Cisco-Talos/cvdupdate/pull/47  

I intend to try to help finish cleanup on that and then if you can base your work on that completed effort to extend the features you've added such as dependabot, CI, docker hub publishing - I think that would be best.

One thing to note is that your Dockerfile runs `cvd update` once, and then aims to serve a private mirror with the `cvd serve` feature.  Meanwhile PR #47's Dockerfile aims to run `cvd update` on a schedule and does not offer the `cvd serve` feature.  

I think running `cvd update` regularly makes the most sense for most people.  Using `cvd serve` to host the mirror is less common, and others may have better/different webservers than the shoddy one used by `cvd serve`.  And some people may not wish to host with a webserver at all.   

My recommendation when updating this PR is to make it so the `cvd serve` feature is optional and is default-off.  Perhaps it could be enabled by setting an environment variable before starting the container.

2023-05-25 08:54 UTC, monotek commented
On best practices for docker containers is to be immutable. 
This means a container should not change it contents while running.
Most environments nowdays also enforcing read only filesystems so download of new virus definitions would fail anyway.
The corrrect way to use new definitions would be to build a new container.

2023-05-25 19:24 UTC, micahsnyder commented
And how often would you make a new container?  The whole point of cvdupdate is to only update if an update is needed.  If you're making a new container from scratch any time you want the latest definitions, you're misusing cvdupdate and evading the system we created intended to reduce data costs.

2023-05-26 08:30 UTC, monotek commented
You could still do it by using a writable volume in a container ;-)

I would still prefer to rebuild my container. This will also update all container dependencies like container image OS, all packages and  libs. As every build get it's own version i also always know wich exact version of the container is running in my cluster.

Such builds / pushes to the registry could be done automatically. This is supported by Github actions via: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule

2023-05-26 16:50 UTC, micahsnyder commented
> You could still do it by using a writable volume in a container ;-)

Yup! So that's how https://github.com/Cisco-Talos/cvdupdate/pull/47 does it.  👍 

> I would still prefer to rebuild my container (at least on a daily basis). This will also update all container dependencies like container image OS, all packages and libs. As every build get it's own version i also always know wich exact version of the container is running in my cluster.
>
> Such builds / pushes to the registry could be done automatically. This is supported by Github actions via: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule

Rebuilding the image daily certainly makes it so you don't have to worry much about CVE's in the base image.  That would be nice.  😄  
Although ideally we would only have to push up a new image if there were actually new versions of the dependencies though.  Best not to waste Docker Hub's bandwidth if there is no real difference in the image.

2023-05-26 20:44 UTC, micahsnyder commented
Ok @monotek merged #47.  

If you're still interested in working on this, now is a good time to update your PR with the volume mount model in mind.

2023-05-30 17:13 UTC, monotek commented
Thanks for the hint.
I'll add some changes later this or next week.

At least the user creation in the entrypoint is wrong and should be moved to the dockerfile itself, as user creation will fill anyway on readonly fs...

2023-05-31 08:55 UTC, ismvru commented
> At least the user creation in the entrypoint is wrong and should be moved to the dockerfile itself

Hello! I agree that this is not correct, I just tried to make the UserID dynamic so that I could adapt to any infrastructure. I would be happy to see the corrected Dockerfile and gain some more experience.

2023-05-31 16:48 UTC, monotek commented
I've adjusted the container (see update pr description above).

Can be tested via:

Cron mode:

```
docker run -it --rm monotek/cvdupdate
```

Serve mode:

```
docker run -it --rm monotek/cvdupdate serve
```

2023-06-22 12:01 UTC, monotek commented
@ismvru & @micahsnyder 
did you have time to have a look?

2023-06-26 10:03 UTC, monotek commented
i updated the pr to use ghcr.io, as no extra github secrets are needed for this.

2023-08-22 11:34 UTC, monotek commented
friendly ping :)

2024-03-06 13:58 UTC, uudecode commented
tbh, a little problem exists with file  "/root/.cvdupdate/state.json"
it changes every update, and create new docker layer for this changes. Better to move state.json into mounted directory.

2024-03-06 14:59 UTC, monotek commented
You mean "/cvdupdate/.cvdupdate/state.json"?
Is this not wanted as it contains the "last modified" & "last checked" fields with the timestamps?
If we would remove the file the information about the state of the clamav databse in the container would be lost.

2024-10-15 19:30 UTC, micahsnyder requested changes
I'm really sorry I neglected this for so long. I don't have any excuse.

I have some concern with things in this PR.

I love adding `.github/workflows/ci.yaml`. The dependabot change seems good to me and a positive change. If you made this a separate PR I'd be happy to merge that. 

I don't wan to add the release drafter stuff. I'm happy enough doing manual release notes. I'll add them to each release going forward. 

The change to create the user in the Dockerfile instead of the entrypoint seems like a mild improvement, though we still need sudo (or gosu). I don't know the benefit of switching from gosu to sudo other than reducing the image size(?). I'm not sure if there is any other technical benefit or drawback of dropping gosu. 

I see the logic to not use sudo/gosu if USER_ID == 0 is gone. I assume that's ... fine?

The permission bit changes on .gitignore and .dockerignore files are fine.

I have mixed feelings about publishing a container for cvdupdate and using ghcr.io. 

There are a couple merge conflicts now (pypi.yaml, README.md). Sorry.

2024-10-15 19:30 UTC, micahsnyder commented on .github/workflows/ci.yaml
This is nice. It would be very good to have CI.

2024-10-15 19:31 UTC, micahsnyder commented
If you're done with helping on this project, or otherwise unable -- I'll part it out to grab the CI and dependabot stuff which I know I want. Let me know.

2024-10-25 10:13 UTC, monotek commented
updated the branch.
feel free to use only parts of it if you want.

2025-05-22 10:23 UTC, closed without merging